package cl.arlanditech.dota2calculator.fragments.heroes.model.api.response

import com.google.gson.annotations.SerializedName

data class BaseResponse(@SerializedName(value = "1") val hero1 :HeroResponse,
                        @SerializedName("4") val hero4 :HeroResponse,
                        @SerializedName("5") val hero5 :HeroResponse,
                        @SerializedName("6") val hero6 :HeroResponse,
                        @SerializedName("7") val hero7 :HeroResponse,
                        @SerializedName("8") val hero8 :HeroResponse,
                        @SerializedName("9") val hero9 :HeroResponse,
                        @SerializedName("10") val hero10 : HeroResponse,
                        @SerializedName("11") val hero11 : HeroResponse,
                        @SerializedName("12") val hero12 : HeroResponse,
                        @SerializedName("13") val hero13 : HeroResponse,
                        @SerializedName("14") val hero14 : HeroResponse,
                        @SerializedName("15") val hero15 : HeroResponse,
                        @SerializedName("16") val hero16 : HeroResponse,
                        @SerializedName("17") val hero17 : HeroResponse,
                        @SerializedName("18") val hero18 : HeroResponse,
                        @SerializedName("19") val hero19 : HeroResponse,
                        @SerializedName("20") val hero20 : HeroResponse,
                        @SerializedName("21") val hero21 : HeroResponse,
                        @SerializedName("22") val hero22 : HeroResponse,
                        @SerializedName("23") val hero23 : HeroResponse,
                        @SerializedName("25") val hero25 : HeroResponse,
                        @SerializedName("26") val hero26 : HeroResponse,
                        @SerializedName("27") val hero27 : HeroResponse,
                        @SerializedName("28") val hero28 : HeroResponse,
                        @SerializedName("29") val hero29 : HeroResponse,
                        @SerializedName("30") val hero30 : HeroResponse,
                        @SerializedName("31") val hero31 : HeroResponse,
                        @SerializedName("32") val hero32 : HeroResponse,
                        @SerializedName("33") val hero33 : HeroResponse,
                        @SerializedName("34") val hero34 : HeroResponse,
                        @SerializedName("35") val hero35 : HeroResponse,
                        @SerializedName("36") val hero36 : HeroResponse,
                        @SerializedName("37") val hero37 : HeroResponse,
                        @SerializedName("38") val hero38 : HeroResponse,
                        @SerializedName("39") val hero39 : HeroResponse,
                        @SerializedName("40") val hero40 : HeroResponse,
                        @SerializedName("41") val hero41 : HeroResponse,
                        @SerializedName("42") val hero42 : HeroResponse,
                        @SerializedName("43") val hero43 : HeroResponse,
                        @SerializedName("44") val hero44 : HeroResponse,
                        @SerializedName("45") val hero45 : HeroResponse,
                        @SerializedName("46") val hero46 : HeroResponse,
                        @SerializedName("47") val hero47 : HeroResponse,
                        @SerializedName("48") val hero48 : HeroResponse,
                        @SerializedName("49") val hero49 : HeroResponse,
                        @SerializedName("50") val hero50 : HeroResponse,
                        @SerializedName("51") val hero51 : HeroResponse,
                        @SerializedName("52") val hero52 : HeroResponse,
                        @SerializedName("53") val hero53 : HeroResponse,
                        @SerializedName("54") val hero54 : HeroResponse,
                        @SerializedName("55") val hero55 : HeroResponse,
                        @SerializedName("56") val hero56 : HeroResponse,
                        @SerializedName("57") val hero57 : HeroResponse,
                        @SerializedName("58") val hero58 : HeroResponse,
                        @SerializedName("59") val hero59 : HeroResponse,
                        @SerializedName("60") val hero60 : HeroResponse,
                        @SerializedName("61") val hero61 : HeroResponse,
                        @SerializedName("62") val hero62 : HeroResponse,
                        @SerializedName("63") val hero63 : HeroResponse,
                        @SerializedName("64") val hero64 : HeroResponse,
                        @SerializedName("65") val hero65 : HeroResponse,
                        @SerializedName("66") val hero66 : HeroResponse,
                        @SerializedName("67") val hero67 : HeroResponse,
                        @SerializedName("68") val hero68 : HeroResponse,
                        @SerializedName("69") val hero69 : HeroResponse,
                        @SerializedName("70") val hero70 : HeroResponse,
                        @SerializedName("71") val hero71 : HeroResponse,
                        @SerializedName("72") val hero72 : HeroResponse,
                        @SerializedName("73") val hero73 : HeroResponse,
                        @SerializedName("74") val hero74 : HeroResponse,
                        @SerializedName("75") val hero75 : HeroResponse,
                        @SerializedName("76") val hero76 : HeroResponse,
                        @SerializedName("77") val hero77 : HeroResponse,
                        @SerializedName("78") val hero78 : HeroResponse,
                        @SerializedName("79") val hero79 : HeroResponse,
                        @SerializedName("80") val hero80 : HeroResponse,
                        @SerializedName("81") val hero81 : HeroResponse,
                        @SerializedName("82") val hero82 : HeroResponse,
                        @SerializedName("83") val hero83 : HeroResponse,
                        @SerializedName("84") val hero84 : HeroResponse,
                        @SerializedName("85") val hero85 : HeroResponse,
                        @SerializedName("86") val hero86 : HeroResponse,
                        @SerializedName("87") val hero87 : HeroResponse,
                        @SerializedName("88") val hero88 : HeroResponse,
                        @SerializedName("89") val hero89 : HeroResponse,
                        @SerializedName("90") val hero90 : HeroResponse,
                        @SerializedName("91") val hero91 : HeroResponse,
                        @SerializedName("92") val hero92 : HeroResponse,
                        @SerializedName("93") val hero93 : HeroResponse,
                        @SerializedName("94") val hero94 : HeroResponse,
                        @SerializedName("95") val hero95 : HeroResponse,
                        @SerializedName("96") val hero96 : HeroResponse,
                        @SerializedName("97") val hero97 : HeroResponse,
                        @SerializedName("98") val hero98 : HeroResponse,
                        @SerializedName("99") val hero99 : HeroResponse,
                        @SerializedName("100") val hero100 : HeroResponse,
                        @SerializedName("101") val hero101 : HeroResponse,
                        @SerializedName("102") val hero102 : HeroResponse,
                        @SerializedName("103") val hero103 : HeroResponse,
                        @SerializedName("104") val hero104 : HeroResponse,
                        @SerializedName("105") val hero105 : HeroResponse,
                        @SerializedName("106") val hero106 : HeroResponse,
                        @SerializedName("107") val hero107 : HeroResponse,
                        @SerializedName("108") val hero108 : HeroResponse,
                        @SerializedName("109") val hero109 : HeroResponse,
                        @SerializedName("110") val hero110 : HeroResponse,
                        @SerializedName("111") val hero111 : HeroResponse,
                        @SerializedName("112") val hero112 : HeroResponse,
                        @SerializedName("113") val hero113 : HeroResponse,
                        @SerializedName("114") val hero114 : HeroResponse,
                        @SerializedName("119") val hero119 : HeroResponse,
                        @SerializedName("120") val hero120 : HeroResponse,
                        @SerializedName("121") val hero121 : HeroResponse,
                        @SerializedName("126") val hero126 : HeroResponse,
                        @SerializedName("128") val hero128 : HeroResponse,
                        @SerializedName("129") val hero129 : HeroResponse) {
}