package cl.arlanditech.dota2calculator.model

data class AbilityStat(val abilityId : Int,
                       val gameVersionId : Int,
                       val type : Int,
                       val behavior : Int,
                       val unitTargetType : Int,
                       val unitTargetTeam : Int,
                       val unitTargetFlags : Int,
                       val unitDamageType : Int,
                       val spellImmunity : Int,
                       val modifierSupportValue : Int,
                       val modifierSupportBonus : Int,
                       val isOnCastbar : Boolean,
                       val isOnLearnbar : Boolean,
                       val fightRecapLevel : Int,
                       val isGrantedByScepter : Boolean,
                       val hasScepterUpgrade : Boolean,
                       val maxLevel : Int,
                       val levelsBetweenUpgrade : Int,
                       val requiredLevel : Int,
                       val displayAdditionalHeroes : Boolean,
                       val castRange : List<Int>,
                       val castRangeBuffer : List<Int>,
                       val castPoint : List<Double>,
                       val channelTime : List<Double>,
                       val cooldown : List<Int>,
                       val manaCost : List<Int>,
                       val isUltimate : Boolean,
                       val duration : String,
                       val charges : String,
                       val chargeRestoreTime : String) {
}