package cl.arlanditech.dota2calculator.model

import cl.arlanditech.dota2calculator.model.database.entities.HeroStatEntity

data class HeroStat(val gameVersionId : Int,
                    val enabled : Boolean,
                    val heroUnlockOrder : Int,
                    val team : Boolean,
                    val cmEnabled : Boolean,
                    val newPlayerEnabled : Boolean,
                    val attackType : String,
                    val startingArmor : Double,
                    val startingMagicArmor : Int,
                    val startingDamageMin : Int,
                    val startingDamageMax : Int,
                    val attackRate : Double,
                    val attackAnimationPoint : Double,
                    val attackAcquisitionRange : Int,
                    val attackRange : Int,
                    val primaryAttribute : String,
                    val heroPrimaryAttribute : Int,
                    val strengthBase : Int,
                    val strengthGain : Double,
                    val intelligenceBase : Int,
                    val intelligenceGain : Double,
                    val agilityBase : Int,
                    val agilityGain : Double,
                    val hpRegen : Int,
                    val mpRegen : Int,
                    val moveSpeed : Int,
                    val moveTurnRate : Double,
                    val hpBarOffset : Int,
                    val visionDaytimeRange : Int,
                    val visionNighttimeRange : Int ) {
    fun toEntity(): HeroStatEntity {
        val entity = HeroStatEntity(
            gameVersionId = gameVersionId,
            enabled = enabled,
            heroUnlockOrder = heroUnlockOrder,
            team = team,
            cmEnabled = cmEnabled,
            newPlayerEnabled = newPlayerEnabled,
            attackType = attackType,
            startingArmor = startingArmor,
            startingMagicArmor = startingMagicArmor,
            startingDamageMin = startingDamageMin,
            startingDamageMax = startingDamageMax,
            attackRate = attackRate,
            attackAnimationPoint = attackAnimationPoint,
            attackAcquisitionRange = attackAcquisitionRange,
            attackRange = attackRange,
            primaryAttribute = primaryAttribute,
            heroPrimaryAttribute = heroPrimaryAttribute,
            strengthGain = strengthGain,
            strengthBase = strengthBase,
            agilityGain = agilityGain,
            agilityBase = agilityBase,
            intelligenceGain = intelligenceGain,
            intelligenceBase = intelligenceBase,
            hpRegen = hpRegen,
            mpRegen = mpRegen,
            moveSpeed = moveSpeed,
            moveTurnRate = moveTurnRate,
            hpBarOffset = hpBarOffset,
            visionNighttimeRange = visionNighttimeRange,
            visionDaytimeRange = visionDaytimeRange
        )

        return entity
    }
}